import { Router, Request, Response } from 'express';

import { authenticate, authorize, require2FA } from '../auth/authMiddleware';
import { logAudit } from '../services/auditService';
import { Setting } from '../models/index';

const router = Router();


// ─── Default settings per section ─────────────────────────────────────────────

const DEFAULTS: Record<string, Record<string, any>> = {
  branding: {
    companyName: 'RISO HOME',
    platformName: 'RISO HUB',
    primaryColour: '#7A8465',
    logoUrl: null,
  },
  notifications: {
    emailEnabled: true,
    weeklyDigestEnabled: true,
    qualExpiryDigestEnabled: true,
    complaintAlertsEnabled: true,
    mentionEmailsEnabled: true,
    signatureEmailsEnabled: true,
  },
  documents: {
    defaultDocType: 'handover',
    includeWarrantySection: true,
    includeRiskAssessment: false,
    footerText: 'Generated by RISO HUB — MCS Compliant',
  },
  agents: {
    workflowAgentEnabled: true,
    complianceAgentEnabled: true,
    reminderAgentEnabled: false,
  },
  signatures: {
    expiryDays: 7,
    allowAdminOverride: true,
    requireCustomerSignature: true,
    requireInstallerSignature: false,
  },
  storage: {
    s3BucketName: process.env.AWS_S3_BUCKET || '',
    driveEnabled: true,
    driveRootFolderId: process.env.GOOGLE_DRIVE_ROOT_FOLDER_ID || '',
    maxFileSizeMb: 50,
  },
  dataRetention: {
    projectRetentionYears: 7,
    auditLogRetentionYears: 10,
    softDeleteDays: 30,
  },
  integrations: {
    heatEngineerEnabled: false,
    busCheckerEnabled: false,
    epcEnabled: false,
  },
  security: {
    jwtAccessExpiryMinutes: 15,
    jwtRefreshExpiryDays: 7,
    accountLockoutAttempts: 5,
    accountLockoutMinutes: 15,
    requireAdminTwoFactor: true,
    allowUserTwoFactor: true,
  },
  auditLog: {
    retainDays: 3650, // 10 years
    exportEnabled: true,
  },
  dangerZone: {
    maintenanceMode: false,
    allowHardDelete: false,
  },
};

// ─── Helper — get all settings for a section as a flat key/value object ───────

async function getSectionSettings(section: string): Promise<Record<string, any>> {
  const rows = await Setting.findAll({ where: { section } });
  const stored = Object.fromEntries(rows.map(r => [r.key, r.value]));
  // Merge stored over defaults so new defaults appear even if not yet in DB
  return { ...DEFAULTS[section], ...stored };
}

// ─── GET /api/settings ────────────────────────────────────────────────────────
// Returns all 11 sections

router.get('/', authenticate, authorize('Admin'), async (req: Request, res: Response) => {
  try {
    const sections = Object.keys(DEFAULTS);
    const result: Record<string, any> = {};

    for (const section of sections) {
      result[section] = await getSectionSettings(section);
    }

    res.json(result);
  } catch (err) {
    console.error('GET /api/settings error:', err);
    res.status(500).json({ error: 'Failed to fetch settings' });
  }
});

// ─── GET /api/settings/:section ───────────────────────────────────────────────

router.get('/:section', authenticate, authorize('Admin'), async (req: Request, res: Response) => {
  try {
    const { section } = req.params;

    if (!DEFAULTS[section]) {
      return res.status(404).json({ error: `Unknown settings section: ${section}` });
    }

    const settings = await getSectionSettings(section);
    res.json({ section, settings });
  } catch (err) {
    console.error('GET /api/settings/:section error:', err);
    res.status(500).json({ error: 'Failed to fetch settings section' });
  }
});

// ─── PATCH /api/settings/:section ────────────────────────────────────────────
// 2FA required for all settings mutations

router.patch('/:section', authenticate, authorize('Admin'), require2FA, async (req: Request, res: Response) => {
  try {
    const { section } = req.params;
    const updates = req.body;

    if (!DEFAULTS[section]) {
      return res.status(404).json({ error: `Unknown settings section: ${section}` });
    }

    // Only allow keys that exist in defaults for this section
    const allowedKeys = Object.keys(DEFAULTS[section]);
    const rejected = Object.keys(updates).filter(k => !allowedKeys.includes(k));

    if (rejected.length > 0) {
      return res.status(400).json({ error: `Unknown keys for section ${section}: ${rejected.join(', ')}` });
    }

    const oldSettings = await getSectionSettings(section);

    // Upsert each key
    for (const [key, value] of Object.entries(updates)) {
      await Setting.upsert({ section, key, value, updatedBy: req.user!.id });
    }

    const newSettings = await getSectionSettings(section);

    await logAudit({
      userId: req.user!.id,
      action: 'settings.updated',
      entityType: 'Settings',
      entityId: section,
      oldValue: oldSettings,
      newValue: newSettings,
      ipAddress: req.ip,
      metadata: { section, keysChanged: Object.keys(updates) },
    });

    res.json({ section, settings: newSettings });
  } catch (err) {
    console.error('PATCH /api/settings/:section error:', err);
    res.status(500).json({ error: 'Failed to update settings' });
  }
});

export default router;
